# Generated by Selenium IDE
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from datetime import datetime, timedelta
n=int(input())
path='D:\\nifty\\'
options = webdriver.ChromeOptions()
options.add_argument("--window-size=1920,1080")
options.add_argument("--start-maximized")
prefs = {'download.default_directory' : path }
options.add_experimental_option('prefs', prefs)
driver = webdriver.Chrome(r'chromedriver.exe',options=options)
driver.get("https://www1.nseindia.com/products/content/derivatives/equities/historical_fo.htm")
x=input()
for types in  ['CE','PE'] :
 x=input()
 date=datetime.now()
 for i in range(n) :
  date1=date
  date=date-timedelta(days=85)
  driver.find_element(By.ID, "fromDate").click()
  driver.find_element(By.ID, "fromDate").send_keys(date.strftime('%d/%m/%Y'))
  driver.find_element(By.ID, "toDate").click()
  driver.find_element(By.ID, "toDate").send_keys(date1.strftime('%d/%m/%Y'))
  driver.execute_script('document.querySelector("#getButton").click();')
  while True :
      try :
        driver.find_element(By.LINK_TEXT, "Download file in csv format").click()
        break
      except :
          time.sleep(0.5)
  
